name = "not-today-api"
main = "worker/index.js"
compatibility_date = "2023-07-10"

[site]
bucket = "./dist"

[build]
command = "npm run build"

[routes]
pattern = "*/api/*"
zone_name = "your-domain.com" # 替换为你的实际域名

[env.production]
route = "your-domain.com/api/*" # 替换为你的实际域名 