name = "not-today-api"
main = "worker/index.js"
compatibility_date = "2023-07-10"

[site]
bucket = "./dist"

[build]
command = "npm run build"

[routes]
pattern = "*/api/*"
zone_name = "messwithtime.com" # 已更新为实际域名

[env.production]
route = "messwithtime.com/api/*" # 已更新为实际域名 