
name = "mess-with-time-api"
main = "dist/index.js"
compatibility_date = "2023-05-18"

site = {
  bucket = "dist"
  build = {
    command = "npm run build"
    upload = {
      format = "service-worker"
    }
  }
}

[env.production]
route = "*/*"
